# Generated by Django 6.0.2 on 2026-02-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='vehicle_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
