# Generated by Django 6.0.2 on 2026-02-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_riderequest_is_paid_riderequest_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='payout_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('settled', 'Settled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
