# Generated by Django 6.0.2 on 2026-02-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_riderequest_payout_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='service_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
