# Generated by Django 6.0.2 on 2026-02-17 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taluk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taluks', to='location.district')),
            ],
            options={
                'unique_together': {('district', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Panchayath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('taluk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panchayaths', to='location.taluk')),
            ],
            options={
                'unique_together': {('taluk', 'name')},
            },
        ),
    ]
