# Generated by Django 6.0.2 on 2026-02-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin_otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
