# Generated by Django 6.0.2 on 2026-02-10 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='DriverApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('experience_years', models.PositiveIntegerField()),
                ('service_type', models.CharField(choices=[('driver_only', 'Driver Only'), ('driver_with_vehicle', 'Driver With Vehicle')], max_length=30)),
                ('license_document', models.FileField(upload_to='driver_documents/licenses/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
