# Generated by Django 6.0.2 on 2026-02-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_remove_driverprofile_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverapplication',
            name='profile_image',
            field=models.ImageField(default=1, upload_to='profiles/'),
            preserve_default=False,
        ),
    ]
