# Generated by Django 6.0.2 on 2026-02-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driverapplication_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='profile_image',
            field=models.ImageField(default=1, upload_to='profiles/'),
            preserve_default=False,
        ),
    ]
