# Generated by Django 6.0.2 on 2026-02-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driverprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='profile_image',
        ),
    ]
