# Generated by Django 6.0.2 on 2026-02-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_remove_driverprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverapplication',
            name='license_document',
            field=models.FileField(upload_to='media/driver_documents/licences'),
        ),
        migrations.AlterField(
            model_name='driverapplication',
            name='profile_image',
            field=models.ImageField(upload_to='media/profiles/'),
        ),
    ]
