# Generated by Django 6.0.2 on 2026-02-12 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_vehicletype_brand_vehiclevariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='drivers.vehicletype'),
        ),
        migrations.AlterField(
            model_name='vehiclevariant',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='drivers.brand'),
        ),
    ]
