# Generated by Django 6.0.2 on 2026-02-12 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_alter_brand_vehicle_type_alter_vehiclevariant_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='vehiclevariant',
            name='brand',
        ),
        migrations.DeleteModel(
            name='VehicleType',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='VehicleVariant',
        ),
    ]
