# Generated by Django 6.0.2 on 2026-02-12 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0009_remove_brand_vehicle_type_and_more'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverapplication',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='driverapplication',
            name='vehicle_registration_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='vehicle_registration_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='driverapplication',
            name='license_document',
            field=models.FileField(upload_to='driver_documents/licenses/'),
        ),
        migrations.AlterField(
            model_name='driverapplication',
            name='profile_image',
            field=models.ImageField(upload_to='profiles/'),
        ),
    ]
