# Generated by Django 6.0.2 on 2026-02-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0012_alter_driverapplication_license_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverapplication',
            name='license_document',
            field=models.FileField(upload_to='driver_documents/licenses/'),
        ),
        migrations.AlterField(
            model_name='driverapplication',
            name='profile_image',
            field=models.ImageField(upload_to='profiles/'),
        ),
    ]
