# Generated by Django 6.0.2 on 2026-02-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0013_alter_driverapplication_license_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
