# Generated by Django 6.0.2 on 2026-02-17 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0015_remove_driverapplication_rejection_reason_and_more'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='panchayath',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='location.panchayath'),
            preserve_default=False,
        ),
    ]
