# Generated by Django 6.0.2 on 2026-02-17 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0016_driverprofile_panchayath'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverapplication',
            name='panchayath',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='location.panchayath'),
            preserve_default=False,
        ),
    ]
