# Generated by Django 6.0.2 on 2026-02-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0017_driverapplication_panchayath'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
