# Generated by Django 6.0.2 on 2026-02-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0019_drivercontactlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivercontactlog',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='drivercontactlog',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
