# Generated by Django 6.0.2 on 2026-02-18 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0020_drivercontactlog_destination_and_more'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverapplication',
            name='insurance_document',
            field=models.FileField(blank=True, null=True, upload_to='driver_documents/insurance/'),
        ),
        migrations.AddField(
            model_name='driverapplication',
            name='rc_document',
            field=models.FileField(blank=True, null=True, upload_to='driver_documents/rc/'),
        ),
        migrations.AddField(
            model_name='driverapplication',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.CreateModel(
            name='DriverVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20)),
                ('vehicle_image', models.ImageField(upload_to='vehicle_images/')),
                ('rc_document', models.FileField(upload_to='driver_documents/rc/')),
                ('insurance_document', models.FileField(upload_to='driver_documents/insurance/')),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='drivers.driverprofile')),
                ('vehicle_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.vehiclecategory')),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.vehiclemodel')),
            ],
        ),
    ]
