# Generated by Django 6.0.2 on 2026-02-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0021_driverapplication_insurance_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivervehicle',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
