# Generated by Django 6.0.2 on 2026-02-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0022_drivervehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
