# Generated by Django 6.0.2 on 2026-02-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0023_driverprofile_is_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverContactLog',
        ),
    ]
