# Generated by Django 6.0.2 on 2026-02-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0024_delete_drivercontactlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='razorpay_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
