# Generated by Django 6.0.2 on 2026-02-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0025_driverprofile_razorpay_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
