# Generated by Django 6.0.2 on 2026-02-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0026_driverprofile_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
